title: YaniQ Enterprise E-Commerce Platform
description: Comprehensive documentation for YaniQ - A cloud-native microservices-based e-commerce platform built with Spring Boot, Spring Cloud, and modern DevOps practices.
baseurl: "/Yaniq_docs"
url: "https://giglox-dev.github.io"
repository: GIGLOX-DEV/Yaniq_docs

remote_theme: just-the-docs/just-the-docs

# Markdown processor
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

color_scheme: nil
search_enabled: true
search:
  heading_level: 2
  previews: 3
  tokenizer_separator: /[\s\-]+/
  rel_url: true
  button: true

# Logo and favicon
logo: "/Yaniq_docs/assets/images/logo.png"
favicon_ico: "/Yaniq_docs/assets/images/favicon.ico"

# Footer content
footer_content: "<p>© 2024-2025 YaniQ Enterprise. Licensed under <a href='https://www.apache.org/licenses/LICENSE-2.0'>Apache License 2.0</a>. Built with ❤️ using Spring Boot & Spring Cloud.</p><p>For support, visit <a href='https://github.com/GIGLOX-DEV/Yaniq_docs/issues'>GitHub Issues</a></p>"

# Aux links for the upper right navigation
aux_links:
  "GitHub Repository":
    - "https://github.com/GIGLOX-DEV/YaniQ"
  "Managed Documentation":
    - "/Yaniq_docs/pages/reference/managed-documentation.html"

# Aux links open in new tab
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Heading anchor links
heading_anchors: true

# External navigation links
nav_external_links:
  - title: YaniQ Main Site
    url: https://yaniq.com
    hide_icon: false

# Collections
collections:
  services:
    permalink: "/Yaniq_docs/services/:path/"
    output: true
  libraries:
    permalink: "/Yaniq_docs/libraries/:path/"
    output: true

# Collection defaults
defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "default"
      parent: "Services"
  - scope:
      path: ""
      type: "libraries"
    values:
      layout: "default"
      parent: "Libraries"
  - scope:
      path: "pages/getting-started"
    values:
      layout: "default"
      parent: "Getting Started"
  - scope:
      path: "pages/guides"
    values:
      layout: "default"
      parent: "Guides"
  - scope:
      path: "pages/reference"
    values:
      layout: "default"
      parent: "Reference"
  - scope:
      path: "pages/contributing"
    values:
      layout: "default"
      parent: "Contributing"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Enable plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - deploy.sh
  - DEPLOYMENT_SUMMARY.md
  - CONTRIBUTING.md

# SEO settings
github:
  repository_url: "https://github.com/GIGLOX-DEV/Yaniq_docs"
  repository_name: "GIGLOX-DEV/Yaniq_docs"

# Callouts configuration
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Code copy button
enable_copy_code_button: true

# Mermaid diagrams support
mermaid:
  version: "10.6.1"
