title: YaniQ Enterprise E-Commerce Platform
description: Comprehensive documentation for YaniQ - A cloud-native microservices-based e-commerce platform built with Spring Boot, Spring Cloud, and modern DevOps practices.
baseurl: "/Yaniq_docs"
url: "https://giglox-dev.github.io"

remote_theme: just-the-docs/just-the-docs

# Markdown processor
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

color_scheme: auto
search_enabled: true
search:
  heading_level: 2
  previews: 3
  tokenizer_separator: /[\s\-]+/
  rel_url: true
  button: true

# Logo and favicon
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"

# Footer content
footer_content: "<p>© 2024-2025 YaniQ Enterprise. Licensed under <a href='https://www.apache.org/licenses/LICENSE-2.0'>Apache License 2.0</a>. Built with ❤️ using Spring Boot & Spring Cloud.</p><p>For support, visit <a href='https://github.com/GIGLOX-DEV/Yaniq_docs/issues'>GitHub Issues</a></p>"

# Aux links for the upper right navigation
aux_links:
  "GitHub Repository":
    - "https://github.com/GIGLOX-DEV/YaniQ"
  "Report Issue":
    - "https://github.com/GIGLOX-DEV/Yaniq_docs/issues/new"
  "Managed Documentation":
    - "/managed-documentation"

# Aux links open in new tab
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Heading anchor links
heading_anchors: true

# External navigation links
nav_external_links:
  - title: YaniQ Main Site
    url: https://yaniq.com
    hide_icon: false

# Collections
collections:
  services:
    permalink: "/:collection/:path/"
    output: true
  libraries:
    permalink: "/:collection/:path/"
    output: true
  guides:
    permalink: "/:collection/:path/"
    output: true

# Collection defaults
defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "default"
      parent: "Services"
  - scope:
      path: ""
      type: "libraries"
    values:
      layout: "default"
      parent: "Libraries"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "default"
      parent: "Guides"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Enable plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - deploy.sh
  - DEPLOYMENT_SUMMARY.md
  - README.md

# SEO settings
github:
  repository_url: "https://github.com/GIGLOX-DEV/YaniQ"
  repository_name: "GIGLOX-DEV/YaniQ"

# Google Analytics (optional - add your tracking ID)
# ga_tracking: UA-XXXXXXXX-X

# Callouts configuration
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Code copy button
enable_copy_code_button: true

# Mermaid diagrams support
mermaid:
  version: "10.6.1"
