name: Test Documentation Build

on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/test-docs.yml'

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0

      - name: Install dependencies
        run: |
          cd docs
          bundle install

      - name: Build Jekyll site
        run: |
          cd docs
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Test HTML
        run: |
          cd docs
          bundle exec htmlproofer ./_site --disable-external --allow-hash-href
        continue-on-error: true

      - name: Check for broken links
        run: |
          echo "✅ Documentation build successful"
